version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/node-socket"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node-socket
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
